$(document).ready(function(){
            $(".hambuger").click(function(){
                $(".header_nav").slideToggle();
            });
            $(window).resize(function(){
                if(window.innerWidth>=1240){
                    $(".header_nav").show();
                }
            });
            $(window).resize(function(){
                if(window.innerWidth>=768&&window.innerWidth<=1239){
                    $(".header_nav").hide();
                }
            });
            $(window).resize(function(){
                if(window.innerWidth<=767){
                    $(".header_nav").hide();
                }
            });
        });